version: '2'
services:
  cgi:
    build:
      context: ./
      dockerfile: cgi.dockerfile
    working_dir: /var/www
    volumes:
      - ${APPLICATION}:/var/www
      - ${LOGS_DIR}:/tmp/logs/
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"

  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - cgi
    ports:
      - ${PORT}:80

  db:
    image: mysql:${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306